// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzrsvyztiggspncumojh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16cnN2eXp0aWdnc3BuY3Vtb2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NjIyNjMsImV4cCI6MjA3MTAzODI2M30.NM_kxHQhFku0EJUZerT4fDXSewIv00U02_oFZg15mgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});